{{- if .Values.ui.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "ghost-platform.componentName" (list . "ui") }}
  labels:
    app.kubernetes.io/name: {{ include "ghost-platform.fullname" . }}
    app.kubernetes.io/component: ui
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  type: {{ .Values.ui.service.type }}
  selector:
    app.kubernetes.io/name: {{ include "ghost-platform.fullname" . }}
    app.kubernetes.io/component: ui
  ports:
    - name: http
      port: {{ .Values.ui.service.port }}
      targetPort: {{ .Values.ui.service.port }}
{{- end }}
