"""Token validation utilities for the VNC gateway service.

Tokens are generated by the public Gateway and embedded into requests that
reach this service.  The validator ensures that the tokens are authentic HS256
JSON Web Tokens created by :class:`services.gateway.app.security.vnc.VncTokenService`
and that the claims match the requested session identifier.
"""

from __future__ import annotations

import logging
from dataclasses import dataclass
from datetime import UTC, datetime
from typing import Any

from jose import JWTError, jwt

LOG = logging.getLogger(__name__)


class TokenValidationError(ValueError):
    """Raised when the provided VNC token cannot be validated."""


@dataclass(slots=True)
class TokenValidator:
    """Validate VNC access tokens tied to a session identifier.

    Tokens are expected to be HS256 JWTs containing the claims issued by the
    public Gateway: ``sid`` (session identifier), ``exp`` (expiry timestamp),
    ``iss`` (issuer identifier), and optional ``sub`` (authenticated subject).
    The validator ensures that the signature is valid, the token has not
    expired, the issuer matches the configured expectation, and the ``sid``
    claim equals the session identifier extracted from the request path.

    Parameters
    ----------
    secret:
        Shared secret string agreed upon with the public Gateway service.
    issuer:
        Expected issuer claim embedded into gateway-generated tokens. Defaults
        to ``"camou-gateway"``.
    """

    secret: str
    issuer: str = "camou-gateway"

    def _decode(self, token: str) -> dict[str, Any]:
        """Decode the provided JWT and return its claims.

        Parameters
        ----------
        token:
            HS256 encoded JWT issued by the public Gateway.

        Returns
        -------
        dict[str, Any]
            Parsed claims contained within the JWT.

        Raises
        ------
        TokenValidationError
            If the token cannot be decoded or fails signature/expiry checks.
        """

        if not token:
            raise TokenValidationError("Token is required")

        try:
            return jwt.decode(
                token,
                self.secret,
                algorithms=["HS256"],
                issuer=self.issuer,
                options={"require_exp": True, "verify_aud": False},
            )
        except JWTError as exc:
            raise TokenValidationError("Token verification failed") from exc

    def validate(self, session_id: str, token: str) -> None:
        """Validate that ``token`` authorises access to ``session_id``.

        Parameters
        ----------
        session_id:
            Target session identifier.
        token:
            HS256 JWT produced by the Gateway.

        Raises
        ------
        TokenValidationError
            If the token is missing, malformed, expired, issued for a different
            session, or signed with the wrong secret.

        Examples
        --------
        >>> validator = TokenValidator(secret="s")
        >>> token = "..."  # JWT issued by the Gateway
        >>> validator.validate("abc", token)
        """

        claims = self._decode(token)

        claim_session_id = claims.get("sid")
        if claim_session_id != session_id:
            raise TokenValidationError("Token was issued for a different session")

        exp = claims.get("exp")
        if not isinstance(exp, int):
            raise TokenValidationError("Token is missing an expiration timestamp")

        now = datetime.now(tz=UTC)
        if now >= datetime.fromtimestamp(exp, tz=UTC):
            raise TokenValidationError("Token has expired")

        LOG.debug("VNC token validated", extra={"session_id": session_id})


__all__ = ["TokenValidationError", "TokenValidator"]
