"""Token validation utilities for the VNC gateway service.

Tokens are generated by the public Gateway and embedded into requests that
reach this service.  The validator implements a straightforward HMAC based
scheme which ensures that tokens are scoped to a particular session identifier
and cannot be tampered with without knowledge of the shared secret.
"""

from __future__ import annotations

import base64
import hmac
import logging
from dataclasses import dataclass
from hashlib import sha256

LOG = logging.getLogger(__name__)


class TokenValidationError(ValueError):
    """Raised when the provided VNC token cannot be validated."""


@dataclass(slots=True)
class TokenValidator:
    """Validate VNC access tokens tied to a session identifier.

    The expected token format is ``base64url(session_id || ":" || signature)``
    where ``signature`` is an HMAC-SHA256 digest calculated over the plain-text
    session identifier using the shared secret.  This simple format is
    sufficient for the initial milestone and keeps the validator small and
    deterministic which simplifies unit testing.

    Parameters
    ----------
    secret:
        Shared secret string agreed upon with the public Gateway service.
    """

    secret: str

    def _expected_signature(self, session_id: str) -> str:
        """Compute the expected hex digest for ``session_id``.

        Parameters
        ----------
        session_id:
            Unique session identifier issued by the Runner.

        Returns
        -------
        str
            Hex encoded HMAC-SHA256 signature.
        """

        digest = hmac.new(self.secret.encode("utf-8"), session_id.encode("utf-8"), sha256)
        return digest.hexdigest()

    def validate(self, session_id: str, token: str) -> None:
        """Validate that ``token`` matches the expected signature.

        Parameters
        ----------
        session_id:
            Target session identifier.
        token:
            Base64 URL encoded token produced by the Gateway.

        Raises
        ------
        TokenValidationError
            If the token is missing, malformed or does not match the expected
            signature for the provided session identifier.

        Examples
        --------
        >>> validator = TokenValidator(secret="s")
        >>> token = validator.issue("abc")
        >>> validator.validate("abc", token)
        """

        if not token:
            raise TokenValidationError("Token is required")

        try:
            decoded = base64.urlsafe_b64decode(token.encode("ascii")).decode("utf-8")
        except (ValueError, UnicodeDecodeError) as exc:
            raise TokenValidationError("Token is not valid base64") from exc

        try:
            token_session_id, signature = decoded.split(":", 1)
        except ValueError as exc:  # pragma: no cover - defensive programming
            raise TokenValidationError("Token structure is invalid") from exc

        if token_session_id != session_id:
            raise TokenValidationError("Token was issued for a different session")

        expected = self._expected_signature(session_id)
        if not hmac.compare_digest(signature, expected):
            LOG.warning("Token validation failed", extra={"session_id": session_id})
            raise TokenValidationError("Token signature mismatch")

    def issue(self, session_id: str) -> str:
        """Issue a token for ``session_id`` (test helper).

        This method is primarily meant for tests and local tooling.  It mirrors
        :meth:`validate` by emitting tokens following the same scheme which
        keeps fixtures concise without having to re-implement the signing logic
        inline within tests.
        """

        payload = f"{session_id}:{self._expected_signature(session_id)}"
        return base64.urlsafe_b64encode(payload.encode("utf-8")).decode("ascii")


__all__ = ["TokenValidationError", "TokenValidator"]
